### ISSUE TITLE
dependency to ember moment is missing

### ISSUE THREAD

**Issue by justastefan** [devotox/ember-paper-pikaday#3]
not critical

**Comment by devotox** [comment]
@justastefan should this be a dependency or dev-dependency? can you make a PR?

**Comment by justastefan** [comment]
A dependency.

Am 20.11.2017 2:44 nachm. schrieb "Devonte" <notifications@github.com>:

**Comment by devotox** [comment]
Fixed in https://github.com/devotox/ember-paper-pikaday/releases/tag/v1.0.1
