### ISSUE TITLE
Format value

### ISSUE THREAD

**Issue by patodevilla** [devotox/ember-paper-pikaday#6]
this library appears to set the value in the model in a formatted way e.i DD/MM/YYYY. Is there a way to display it as such and set the value in a iso8601 format? I tried the same code directly with ember-pikaday and it works like a charm.

thanks!

**Comment by devotox** [comment]
I will create an option flag that allows you to get the iso8601 format

**Comment by devotox** [comment]
Actually due to the way Ember Paper input works you can only get the value set in the field so the display value. What you can do is use moment to then change the value to iso8601 when you want to send it to an API or something
