### ISSUE TITLE
Update ember-pikaday

### ISSUE THREAD

**Issue by alanlalonde** [devotox/ember-paper-pikaday#7]
After two years, [ember-pikaday](https://github.com/adopted-ember-addons/ember-pikaday/releases) has finally been updated and the latest release as of this ticket's creation is 2.3.0, which fixes a large number of NPM and EmberJS deprecations. Would it be possible to roll an update of the package into a new release of ember-paper-pikaday?

Thanks

**Comment by devotox** [comment]
@alanlalonde Just saw this my apologies. Would you be able to do this and send a PR?

**Comment by gnucifer** [comment]
Thanks for a wonderful component! I could also look into it if @alanlalonde does not get there before me.

**Comment by devotox** [comment]
That would be great thank you!

**Comment by alanlalonde** [comment]
Hadn't checked this ticket ever since the original PR comment, but it's most definitely completed and can now be closed. Thanks again!
